# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities


class Test():
    def setup_method(self, method):
        self.driver = webdriver.Firefox()
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def test(self):
        self.driver.get("https://tutorialsninja.com/demo/index.php?route=account/register")
        self.driver.find_element(By.ID, "input-firstname").click()
        self.driver.find_element(By.NAME, "lastname").click()
        self.driver.find_element(By.ID, "input-email").click()
        self.driver.find_element(By.ID, "input-password").click()
        self.driver.find_element(By.ID, "input-confirm").click()
        self.driver.find_element(By.XPATH, "//input[@name=\'newsletter\' and @value=\'1\']").click()
        self.driver.find_element(By.NAME, "agree").click()
        self.driver.find_element(By.XPATH, "//input[@value=\'Continue\']").click()
        elements = self.driver.find_elements(By.XPATH, "//h1")
        assert len(elements) > 0


